# Generated by Django 3.2.18 on 2023-06-03 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name="Ім'я")),
                ('image', models.ImageField(blank=True, null=True, upload_to='authors/', verbose_name='Фото')),
                ('biography', models.TextField(blank=True, null=True, verbose_name='Біографія')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Заповнюється автоматично')),
            ],
            options={
                'verbose_name': 'автора',
                'verbose_name_plural': 'Автори',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва книги')),
                ('cover_image', models.ImageField(upload_to='book_covers/', verbose_name='Фото обкладинки')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Ціна')),
                ('slug', models.SlugField(max_length=255, verbose_name='Заповнюється автоматично')),
                ('weight', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Вага')),
                ('edition', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Тираж')),
                ('amount_pages', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Кількість сторінок')),
                ('isbn', models.CharField(blank=True, max_length=255, null=True, verbose_name='ISBN')),
                ('author', models.ManyToManyField(blank=True, related_name='books', to='store.Author', verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'книгу',
                'verbose_name_plural': 'Книжки',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Мова')),
            ],
            options={
                'verbose_name': 'мову',
                'verbose_name_plural': 'Мови',
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Папір')),
            ],
            options={
                'verbose_name': 'папір',
                'verbose_name_plural': 'Папір',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва видавництва')),
                ('image', models.ImageField(blank=True, null=True, upload_to='publishers/', verbose_name='Фото видавництва')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис видавництва')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Заповнюється автоматично')),
            ],
            options={
                'verbose_name': 'видавництво',
                'verbose_name_plural': 'Видавництва',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'категорію', 'verbose_name_plural': 'Категорії'},
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Вміст')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 'Жахливо'), (2, 'Погано'), (3, 'Типово'), (4, 'Чудово'), (5, 'Ідеально')], verbose_name='Рейтинг')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Дата створення')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='store.book', verbose_name='Книга рецензії')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор рецензії')),
            ],
            options={
                'verbose_name': 'рецензію',
                'verbose_name_plural': 'Рецензії',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.category', verbose_name='Категорія'),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.ManyToManyField(blank=True, to='store.Language', verbose_name='Мова'),
        ),
        migrations.AddField(
            model_name='book',
            name='paper',
            field=models.ManyToManyField(blank=True, to='store.Paper', verbose_name='Папір'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ManyToManyField(blank=True, related_name='books', to='store.Publisher', verbose_name='Видавництво'),
        ),
    ]
