# Generated by Django 3.2.18 on 2023-06-02 15:30

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Адреса електронної пошти')),
                ('phone_number', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Неправильний номер телефону. Введіть номер у форматі: "0xxxxxxxxx".', regex='^(0\\d{9})$')], verbose_name='Номер телефону')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name="Ім'я")),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='Прізвище')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активний')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Статус персоналу')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Статус суперкористувача')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Дата приєднання')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'користувача',
                'verbose_name_plural': 'Користувачі',
            },
        ),
    ]
